/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorRegistrarDefecto;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Jose
 */
public class VistaRegistrarDefectos extends javax.swing.JFrame {
    public static final String BTN_REGISTRO_PRIMERA = "Se registra un par de primera";
    public static final String BTN_REPROCESO = "se registra defectos por reproceso";
    public static final String BTN_SEPARAR = "Se registran defectos y se separa el par";
    public static final String BTN_HERMANAR = "hermanar calzados";
    public ArrayList<Integer> defectosDerecho;
    public ArrayList<Integer> defectosIzquierdo;
    /**
     * Creates new form VistaRegistrarDefectos
     */
    public VistaRegistrarDefectos(TablaReproceso tablaReproceso, TablaSeparar tablaSeparar) {
        initComponents();
        mostrarDefectos(tablaReproceso,tablaSeparar);
    }
    
    public void ejecutar(){
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    
    public void setControlador(ControladorRegistrarDefecto controlador){
        jButton1.setActionCommand(BTN_REGISTRO_PRIMERA);
        jButton1.addActionListener(controlador);
        jButton2.setActionCommand(BTN_REPROCESO);
        jButton2.addActionListener(controlador);
        jButton3.setActionCommand(BTN_SEPARAR);
        jButton3.addActionListener(controlador);
        jButton4.setActionCommand(BTN_HERMANAR);
        jButton4.addActionListener(controlador);
    }
    
    public void mostrarDefectos(TablaReproceso tabla1, TablaSeparar tabla2){
        DefaultTableModel modeloA1 = tabla1.mostrarDefectos();
        DefaultTableModel modeloA2 = tabla2.mostrarDefectos();
        jTable1.setModel(modeloA1);
        jTable2.setModel(modeloA2);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(10);
        addCheckBox(1,jTable1);
        addCheckBox(2,jTable1);
        addCheckBox(1,jTable2);
        addCheckBox(2,jTable2);
        
    }
    
    public void addCheckBox(int column, JTable table)
    {
        TableColumn tc = table.getColumnModel().getColumn(column);
        tc.setCellEditor(table.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(table.getDefaultRenderer(Boolean.class));
    }
    
    public boolean IsSelected(int row, int column, JTable table)
    {    
        return table.getValueAt(row, column) != null;                       
    }
    
    public void registrarDefectosDeReproceso(){
        defectosIzquierdo = new ArrayList<>();
        for (int i = 0; i < jTable1.getRowCount(); i++)
        {
            if  ( IsSelected(i, 1, jTable1))
            {
                defectosIzquierdo.add(Integer.parseInt(jTable1.getValueAt(i, 0).toString()));
            }
        }
        
        defectosDerecho = new ArrayList<>();
        for (int i = 0; i < jTable2.getRowCount(); i++)
        {
            if  ( IsSelected(i, 2, jTable2))
            {
                defectosDerecho.add(Integer.parseInt(jTable2.getValueAt(i, 0).toString()));
            }
        }
    }
    
    public void registrarDefectosDeSeparar(){
        defectosIzquierdo = new ArrayList<>();
        for (int i = 0; i < jTable2.getRowCount(); i++)
        {
            if  ( IsSelected(i, 1, jTable2))
            {
                defectosIzquierdo.add(Integer.parseInt(jTable2.getValueAt(i, 0).toString()));
            }
        }
        
        defectosDerecho = new ArrayList<>();
        for (int i = 0; i < jTable2.getRowCount(); i++)
        {
            if  ( IsSelected(i, 2, jTable2))
            {
                defectosDerecho.add(Integer.parseInt(jTable2.getValueAt(i, 0).toString()));
            }
        }
    }

    public ArrayList<Integer> getDefectosDerecho() {
        return defectosDerecho;
    }

    public ArrayList<Integer> getDefectosIzquierdo() {
        return defectosIzquierdo;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Primera");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Defectos");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("Reproceso");

        jButton3.setText("Separacion");

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Hermanar >>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
