/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;

/**
 *
 * @author Leonel
 */
public class VistaPrincipalModelo extends javax.swing.JFrame {
    //public static final String BTN_ALTA_COLOR= "opcion para confirmar un color";
    public static final String BTN_ALTA_MODELO= "opcion para dar de alta un modelo";
    public static final String BTN_MODIFICAR_MODELO= "opcion para modificar un modelo";
    public static final String BTN_BAJA_MODELO= "opcion para dar de baja un modelo";
    /**
     * Creates new form VistaPrincipalModelo
     */
    public VistaPrincipalModelo() {
        initComponents();
    }
    public void ejecutar(){
    this.setVisible(true);
    this.setLocationRelativeTo(null);
    }
    
    public void serControlador(Controlador control){
    btnAltaModelo.setActionCommand(BTN_ALTA_MODELO);
    btnAltaModelo.addActionListener(control);
    btnModificarModelo.setActionCommand(BTN_MODIFICAR_MODELO);
    btnModificarModelo.addActionListener(control);
    btnBajaModelo.setActionCommand(BTN_BAJA_MODELO);
    btnBajaModelo.addActionListener(control);
    }
    /*btnAltaColor.setActionCommand(BTN_ALTA_COLOR);
    btnAltaColor.addActionListener(control);*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAltaModelo = new javax.swing.JButton();
        btnModificarModelo = new javax.swing.JButton();
        btnBajaModelo = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Modelo");

        btnAltaModelo.setText("Alta");

        btnModificarModelo.setText("Modificacion");

        btnBajaModelo.setText("Baja");

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBajaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnModificarModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAltaModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(btnAltaModelo)
                .addGap(28, 28, 28)
                .addComponent(btnModificarModelo)
                .addGap(34, 34, 34)
                .addComponent(btnBajaModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaModelo;
    private javax.swing.JButton btnBajaModelo;
    private javax.swing.JButton btnModificarModelo;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
